### ISSUE TITLE
Consider different name for extension

### ISSUE THREAD

**Issue by jeremyevans** [ruby/erb#32]
@k0kubun Maybe I'm wrong, but I think using `require 'erb.so'` may make it more difficult for JRuby to provide a compatible extension.  Ideally, I think it would be best to `require 'erb/html_escape'` or something similar to make it easier for alternative ruby implementations.  CC @headius to confirm that this would make things easier for JRuby.

I'd like to get the final name for the extension decided before I start using it in Roda and Erubi.

**Comment by k0kubun** [comment]
I didn't work on it since I didn't hear from you again after my last comment in the previous thread, but I can move this forward.

I'm thinking about calling it erb/escape and ERB::Escape. It's shorter than including HTML as well in the module name, and there's still a small possibility to start doing the same thing for url escape to achieve the same optimization or to remove cgi from dependency in case we want to demote cgi to a bundled gem (bundler also uses cgi, so it needs to be resolved as well though).

If I get confirmation from you, I can add it or review/merge any pull request you want to add.

**Comment by headius** [comment]
Yes, `erb/escape` does make it easier for us to provide an equivalent extension. Additionally, should we consider making a separate html/url-escaping gem that both cgi and erb can depend on? I have not been following this closely, but aren't we duplicating logic form `cgi/escape` here?

**Comment by headius** [comment]
Specifically to confirm what @jeremyevans said... we do not recognize .so extensions as being loadable, which is the main problem. If there's a JRuby jar-based extension, we will be able to find it with the bare filename require.

**Comment by k0kubun** [comment]
> should we consider making a separate html/url-escaping gem that both cgi and erb can depend on? I have not been following this closely, but aren't we duplicating logic form cgi/escape here?

This current situation around this is unfortunately intentional; the reason why erb started to have this was to introduce an "incompatibility" that seems intolerable in the cgi side, and adding a parameter to switch it would make the interface ugly and/or perform worse in CRuby.

**Comment by jeremyevans** [comment]
I understand the need for different cgi/erb behavior, and it seems reasonable to me to keep the erb behavior in the erb gem.  I think switching to `require 'erb/escape'` would be best.  If you would like me to work on a pull request, I can probably do that.
